# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shopp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopp

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Functions'
  
  pod 'Alamofire'
  pod 'SwiftyJSON'

  pod 'SVProgressHUD'
  pod 'ESPullToRefresh'

  pod 'MYTableViewIndex'

end
